### ISSUE TITLE
Can the repo size be reduced?

### ISSUE THREAD

**Issue by jbphet** [phetsims/paper-land#1]
@jessegreenberg and I just set up this fork and we each cloned it, and it's quite large.  A `du -sh papyrus` command says that it's 166M, whereas many of our sim repos are around 8M.  Can this be made smaller?  @jessegreenberg says that the `www` directory that is included may be a build artifact that we could omit.  If not that, perhaps some other things can go.

**Comment by BLFiedler** [comment]
Linking this to #26 and also adding the additional goal for this issue to clean up the repo for anything we no longer need from the legacy repo.

**Comment by jessegreenberg** [comment]
We have since learned that the `www` directory is not a build artifact and that media files are manually added to it. The media directory under `www` is ~66 MB. Sounds from quadrilateral account for ~7.5 MB. The heaviest files in media are videos.

**Comment by jessegreenberg** [comment]
During a standup meeting today we discussed replacing the quadrilateral sounds with the optimized versions produced by @Ashton-Morris to help bring down the repo size. Done in the above commit. The files have new names now but I don't think any  programs are currently using them.

**Comment by jessegreenberg** [comment]
Windows reports that paper-land is now 429 MB. That is really big. That report is including `node_modules` and `.git`, both are huge. Most of the rest is in `www`.

Removing my assignment until this is important to work on.

**Comment by brettfiedler** [comment]
I removed some files from the old website, but have introduced more in the docs pages. Eventually I want to move the docs to a different repo. The build of the docs page is in the gh-pages branch. Maybe I will move the docs to a branch as well. Keeping sel assigned for now.

**Comment by brettfiedler** [comment]
Doc branch was created awhile ago. The topic of repo size hasn't come up in awhile so I will close this unless it becomes a problem.
