### ISSUE TITLE
Make editor in Camera interface preview-only

### ISSUE THREAD

**Issue by brettfiedler** [phetsims/paper-land#107]
We are focusing on using the Creator interface as the primary mode of creating programs. Editing full program JS is secondary. 

One immediate TODO:

- [x] Remove edit capabilities from the Camera page. Remove the Save to DB and Delete buttons.

**Suggestions**
- [x] Move the (Program) Delete button to the Editor interface
- [x] Move the New Space functionality to the Editor (Navigate spaces in Camera, but not create them)
    - [ ]  We'll also want to be able to create Spaces in Creator.
- [x] Move the New Program functionality to the Editor
- [x] Make the Preview in the Camera interface collapsible and hidden by default. Give a collapsed header: "Preview Selected Program Code"
- [x] Clean up and remove the Save Alert from the Camera editor.

JG: EDIT - turned suggestions list into checkboxes

**Comment by jessegreenberg** [comment]
If we do this, it will probably make https://github.com/phetsims/paper-land/issues/215 irrelevant. If you cannot edit code on the Camera page, there is no need to block refreshing it when code is pushed to the database.

**Comment by brettfiedler** [comment]
I think we do it and perhaps caution the advanced case where someone opens it in the separate Editor window, within the Editor window itself?

Whadya think?

**Comment by brettfiedler** [comment]
This looks and has worked well, especially with the New Space in Creator. Closing.
