### ISSUE TITLE
What are the ways that global markers should control Creator components

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/paper-land#119]
Programs and global marker support is a feature we would like to add next for Creator. But I am trying to think of how to abstract global markers so that they work with existing components.

For a number, maybe we just count the number of global markers? What else should you be able to do?

**Comment by brettfiedler** [comment]
We decided this should be limited to "number of global markers", but also let us choose based on the color, which adds an extra dimension. So, global markers become something like
`numberOfTotalMarkers`
`numberOfBlueMarkers`
`numberOfRedMarkers`
etc.

**Comment by jessegreenberg** [comment]
This change is complete and merged into the main branch. Closing.
