### ISSUE TITLE
Create controls for OpenCV detection parameters in Camera.html

### ISSUE THREAD

**Issue by brettfiedler** [phetsims/paper-land#127]
I spent time exploring the different options for fine-tuning OpenCV detection to tailor program detection to specific camera devices and lighting conditions.

I was able to get much more reliable detection at farther distances while tweaking these settings in simpleBloblDetector.js. I noted that many of the max parameters are using arbitrarily high numbers, when they do not go above a theoretical maximum of 1.

```js
const defaultParams = {
  thresholdStep: 10,
  minThreshold: 50,
  maxThreshold: 220,
  minRepeatability: 2,
  minDistBetweenBlobs: 10,

  filterByColor: true,
  blobColor: 0,

  filterByArea: true,
  minArea: 25,
  maxArea: 5000,

  filterByCircularity: false,
  minCircularity: 0.8,
  maxCircularity: 1000000,

  filterByInertia: true,

  //minInertiaRatio: 0.6,
  minInertiaRatio: 0.1,
  maxInertiaRatio: 1000000,

  filterByConvexity: true,

  //minConvexity: 0.8,
  minConvexity: 0.95,
  maxConvexity: 1000000,

  faster: false,
  scaleFactor: 4
};
```

Interestingly, these parameters are used again in detectPrograms.js, which turns off inertia filtering and turns on Circularity filtering.

```js
  const videoROI = knobPointsToROI( config.knobPoints, videoMat );
  const clippedVideoMat = videoMat.roi( videoROI );
  const allPoints = simpleBlobDetector( clippedVideoMat, {
    filterByCircularity: true,
    minCircularity: 0.9,
    minArea: 25,
    filterByInertia: false,
    faster: true,
    scaleFactor
  } );
  ```
  A few other notes:
  
  - `faster` is used in the first pass for dot detection, but not on the second for program detection. Turning it off (false) in the second pass notably slows down the framerate. I think adding an option for 'faster' for dot detection is a good move. It should stay on for program detection.
  - The maximum value for `InertiaRatio` is 1. The optimal inertia ratio for a circle is 0.5. I didn't seem substantial improvements to detection here. I did set the bounds from 0.2 to 0.8 (0.3 above and below a perfect circle) and possibly this is a good place to leave it.
  -  Convexity is similar. A perfect circle (max value) is 1. 0.8 did show spurious detections. I settled around 0.9. I am not sure this is a good candidate for optimization.
  - `minRepeatability` refers to the minimum number of times a similar feature needs to appear to be recognized. Keeping this at 2 or above filters out a lot of random detections that only appear once. Leave this at 2.
  - scaleFactor reduces the effective resolution of the image. It means you could miss dots or the gaps between dots. However, it greatly increases performance.
  - I'm not certain on "filter by color", but also didn't dig as deep here. Nothing super noticeable when I tried swapping it. Let's leave it on by default.
 
Factors with large sway here:

  `thresholdStep` - big impact on performance, but also resolution of detection markers. It operates over min to maxThreshold.
  `minThreshold` - Not as big of an impact, but you can theoretically gate on dark background with this.
  `maxThreshold` - Likewise for very bright pixels.
  `minDistBetweenBlobs` - The number of pixels needed to call two detected centers two distinct blobs. Definitely impactful. Noisier images will benefit from this not being too low, but I found myself setting it to 1 pixel given my small program test setup.
 `minArea` - big impact and arguably the one that made it possible for me to raise the camera much higher for detecting full sized programs. This is a parameter in detectPrograms.js as well. We should make sure they are both updated.
`maxArea` - good for filtering out anything that is being mistreated as a marker.

**Comment by brettfiedler** [comment]
Let's replace the Accuracy -> Performance slider in the Detection category and add controls for each of the following parameters

- Checkbox: `faster` for dot detection (simpleBlobDetector.js), default = unchecked (false), label = 'Average Dot Centers'.
- Slider: `thresholdStep` min = 1, max = 25, step = 1, default = 10, label = 'Pixel Value Step Size'
- Slider: `minThreshold`, min = 0, max = 254, step = 1, default = 50, label = 'Minimum Pixel Value' - validation: Must be smaller than maxThreshold
- Slider: `maxThreshold`, min = 1, max = 255, step = 1, default = 230, label = 'Maximum Pixel Value' - validation: Must be larger than minArea
- Slider: `minArea`, min = 5, max = 100, step = 5, default = 25, label = 'Minimum Dot Area (pixels)' - validation: Must be smaller than maxArea
- Slider: `maxArea`, min = 10, max = 1000, step = 5, default = 500, label = 'Maximum Dot Area (pixels)'  - validation: Must be larger than minArea
- Slider: `minDistBetweenBlobs`, min = 1, max = 50, step = 1, default = 10, label = 'Minimum Dot Separation (pixels)'


I'm a little uncertain about those values for minArea and maxArea, since that may vary greatly depending on play area size and paper sizes. What do you think @jessegreenberg? Maybe we should make those number entry instead until we know more about them and not worry about the slider constraints?

**Comment by jessegreenberg** [comment]
OK, an initial pass for this was done. @brettfiedler can you please review?

- For validation, warnings appear below the sliders.
- Values for all of these should be saved to local storage.
- I added a slider for the `scaleFactor`. The default value (or whatever value you happen to have in local storage) modifies all the values you set here. And I have found that detection is best when it is at 1.
- The first time you use paper-land, the values might come from your local storage and not match what these sliders display, maybe try moving each slider/checkbox at least once.

I tested these out on two computers and they are working pretty well so I will go ahead and merge these into main.

**Comment by brettfiedler** [comment]
This is just wonderfully useful and let's us push openCV to it's limits.

It's a lot smoother to see the effect of each slider and so far I'm finding each one we added as helpful for gating features like spurious markers or smaller random features. Here's a fairly stable example that I was unable to cleanly get before with this distance and size of paper!

![image](https://github.com/phetsims/paper-land/assets/47331395/23678182-ed0f-4eec-b2c4-fa4dc8b66059)

I can also run the "Average Dot Centers" aka `faster` with this, though it is a little bit shakier and I need to adjust the minimum separation.

I am calling this good and leaving any naming adjustments to other issues.
