### ISSUE TITLE
Scripts restart each time program is recognized even while still in window

### ISSUE THREAD

**Issue by brettfiedler** [phetsims/paper-land#13]
Can we have scripts not completely restart when they lose detection? In the scripts themselves (pick-up/resume points..?) or in the detection algorithm?

JB via BF: Does each program call a new instance? Can you have the same program twice? This would assist with a “resume” function
Answer: Not at the moment. Can tear paper apart and it continues to recognize it

![Image](https://user-images.githubusercontent.com/47331395/212159760-498926d5-7623-4681-8816-d5a85dc0c01b.png)

**Comment by brettfiedler** [comment]
To address this, I believe some changes have been made to the Board Model. I know we've added protections for when papers are lost, so they can be reintroduced smoothly. I believe this is also related to #98. 

@jessegreenberg , can you comment on the former? Do we have any tactics for programs continuing to run even when detection is lost? I am thinking the PhET sim in an iFrame example.

**Comment by jessegreenberg** [comment]
Yes - If you want to do that you can write the `onProgramAdded` listener to only add the component once on the first detection, and skip implementing the `onProgramRemoved` listener which would usually remove the component/iframe/whatever.

**Comment by brettfiedler** [comment]
This was handled in many ways during the evolution of Display (formerly Board) and Creator. No longer relevant. Closing.
