### ISSUE TITLE
Rename "Edit Component" button to "Save Changes"

### ISSUE THREAD

**Issue by brettfiedler** [phetsims/paper-land#143]
Participants have not recognized "Edit Component" as a "save" button for the component they are currently editing. It's also a bit far down a lot of the time, but we'll address that elsewhere.

Let's
- [ ] Rename "Edit Component" to "Save Changes"

**Comment by jessegreenberg** [comment]
Button has been renamed to "Save Changes" in dev branch.

**Comment by brettfiedler** [comment]
Great! Style comments in #145. This can close whenever.

**Comment by jessegreenberg** [comment]
Great! Merge complete.
