### ISSUE TITLE
Change behavior of Send to Playground

### ISSUE THREAD

**Issue by brettfiedler** [phetsims/paper-land#144]
It's been a lot for participants to click through Edit Component -> Save Project -> Send to Playground for every small change.

Let's
- [x] Have Send to Playground also save the project

**Comment by jessegreenberg** [comment]
This is done in the dev branch.  Sending to the playground now automatically saves the project.

**Comment by brettfiedler** [comment]
Worked in the example I tried. Ready to close whenever.

**Comment by jessegreenberg** [comment]
Great! Merge complete.
