### ISSUE TITLE
Add an optional buffer setting to continue running scripts after program is no longer detected

### ISSUE THREAD

**Issue by brettfiedler** [phetsims/paper-land#153]
JG and BF discussed the problem of flickering program detection. One possible idea is to add a slight delay between loss of program detection the script stopping. Could be a delay for "OnProgramRemoved" or a delay in Jan's code for handling detected program scripts.

This might take a bit of time, let's chat about it a little later if it continues to be frustrating for people.

**Comment by jessegreenberg** [comment]
This has continued to be frustrating so we are going to bump this up in priority!

**Comment by jessegreenberg** [comment]
This was added a little while ago and has been working OK after some initial turbulence. Closing.
