### ISSUE TITLE
Creator: Add a play button to Sound view form to preview currently selected sound.

### ISSUE THREAD

**Issue by brettfiedler** [phetsims/paper-land#165]
Suggestion from a codesigner: 

Add a way to preview sounds, since they are not all known by everyone.

This could be a small play button next to the dropdown that plays the currently selected sound once. 

We would probably want to be able to stop the sound as well in the event someone uploads something lengthy. Play button doubles as play/pause? Assuming that is a standard react/bootstrap component.

**Comment by jessegreenberg** [comment]
This would be nice, I had a wish for this while testing out changes for #239.

**Comment by jessegreenberg** [comment]
Added, closing.
