### ISSUE TITLE
Images default to bounds of paper

### ISSUE THREAD

**Issue by brettfiedler** [phetsims/paper-land#166]
Suggestion from codesigner as we fiddled with setting the scale to match the bounds of the paper.

We make it so image scale can be set to the bounds of the paper.

I think this might be nice default behavior when the image size/scale is not otherwise set in the form or Custom Function field?

**Comment by jessegreenberg** [comment]
We added a function available to view components to automatically scale to a bounds model component. That covers this issue, closing.
