### ISSUE TITLE
Camera: Add reference for Camera repositioning and zoom shortcuts

### ISSUE THREAD

**Issue by brettfiedler** [phetsims/paper-land#168]
Dragging and zooming into the Camera is an important feature! It should be on the interface.

Let's add some reference above the right-top-side of the Camera window along these lines:

Move: Shift + Drag, Shift + Up/Down/Left/Right
Zoom: Shift + Wheel Up/Down, Shift + +/-

Something with more icon-ness would be nice. I put these into the docs:
![image](https://github.com/phetsims/paper-land/assets/47331395/d0cb65d4-7334-4199-a6a1-b5537bbd2178)

**Comment by jessegreenberg** [comment]
This was added. @brettfiedler and I had some back and forth about the layout, we are OK with the current look. A button was also added to reset the transform and position of the video feed.
