### ISSUE TITLE
Camera: Add keyboard shortcuts to move/zoom Camera view

### ISSUE THREAD

**Issue by brettfiedler** [phetsims/paper-land#169]
Hinted at it in #168 , but we need to add keyboard controls to the camera view translation/zoom feature.

My first guess would be (when focused in the camera view), to use

Move: Shift + Up/Down/Left/Right
Zoom: Shift + +/-

We might need to add the ability to keyboard focus the Camera view if that doesn't exist. And let's make it the first tab stop in the screen. Then the sidebar, then the editor below the camera view.

**Comment by jessegreenberg** [comment]
This was done. Since the keyboard listeners were added globally, they work no matter where focus is. I didn't end up changing the traversal order for this. Ill go ahead and close this one, new issues to refine this can be opened.
