### ISSUE TITLE
Voicing didn't work unless "Print Speech" was checked in Interactive Display

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/paper-land#181]
Noticed while working today with @terracoda, I will take a look at why this happened.

**Comment by jessegreenberg** [comment]
I cannot reproduce this unfortunately. I have a theory that the board wasn't actually activated by user input. I would like to make a modal for the board that requires user input before the user can use it to make sure that the audio context is ready.

**Comment by jessegreenberg** [comment]
Board now looks like this until you click in it:

![image](https://github.com/phetsims/paper-land/assets/6396244/8fe0b8e3-2ceb-49ce-9721-37d35ce4d19c)

**Comment by terracoda** [comment]
Ok, I'll try this out.

**Comment by jessegreenberg** [comment]
Great, thanks! It is on the dev branch at the moment.
