### ISSUE TITLE
Possible to keep some documentation in the main/dev branch?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/paper-land#186]
Occasionally it is nice to look for board API documentation in the IDE and keeping it in a separate branch is slightly inconvenient. I think it was moved to keep the size of main down so it may not be worth it or straight forward. Just asking in case it is simple.

**Comment by brettfiedler** [comment]
That makes sense. Let me see if I can find a clean way to include it in the main branch but also easily reference it in the doc website without having the tool running.

**Comment by brettfiedler** [comment]
Yeah I can do this pretty simply with https://github.com/marketplace/actions/repo-file-sync-action. 

Just the Board API file, @jessegreenberg?

**Comment by jessegreenberg** [comment]
Yes please!

**Comment by brettfiedler** [comment]
Okay! I think this is done. Let me know how it looks. Sent it to client/board/doc for both `main` and `dev` branches whenever `docs` is updated. Quite easy to add other files as necessary.

https://github.com/phetsims/paper-land/commit/5f03c26b210a9a15bc8d252798e7732c9b6c0f63

**Comment by jessegreenberg** [comment]
Thank you @brettfiedler, that is great! Was already happy to refer to it in my IDE this morning.
