### ISSUE TITLE
Support debug programs without a camera feed

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/paper-land#197]
The debug programs would often be most useful without a camera feed so that there is no distracting noise. Lets add an option to play with debug programs with no camera feed.

**Comment by brettfiedler** [comment]
We'll be taking care of this issue in #221!

**Comment by brettfiedler** [comment]
Deferred work on #221 means we should work on a simple implementation of this.

**Comment by jessegreenberg** [comment]
This was added in the above commit and seems to be working well.

However, with the camera disabled we can skip expensive work in `detectPrograms` for better performance. I tried it out tonight but the way variables are reused for both camera and debug programs is making it tricky to refactor. Ill have to return to that part next time.

**Comment by jessegreenberg** [comment]
OK! This seems to be working well with better performance by skipping the blob and program detector when the camera is disabled. Merged into main. A checkbox was added to Camera Settings

![image](https://github.com/phetsims/paper-land/assets/6396244/02e1f457-7c8c-4686-87e9-c31aafa370df)

Closing.
