### ISSUE TITLE
Allow user to skip Send to Playground warning

### ISSUE THREAD

**Issue by brettfiedler** [phetsims/paper-land#203]
A request came in to allow a user to skip the warning when sending to playground that you will overwrite the existing programs.

> I also would like an option “do not show this message again” with a checkbox at the bottom here. It would increase workflow for some.
![image](https://github.com/phetsims/paper-land/assets/47331395/0b2e7a87-da0f-4f58-905d-881ad0ba02ae)

This is reasonable and will result in one less button press for savvy users.

**Comment by jessegreenberg** [comment]
This has been added, closing.
