### ISSUE TITLE
Creator: Add legend to Connections and adjust labels

### ISSUE THREAD

**Issue by brettfiedler** [phetsims/paper-land#208]
![image](https://github.com/phetsims/paper-land/assets/47331395/38c2d0ef-0b7c-4727-89e4-0bc60e1a2da7)

While we're rooting around creator - Shall we remove the Connections after each checkbox and turn that word into a header? And then add a small dash line that matches the color of the link beside the label? This will add clarity and shrink the size of the legend.

If it's simple, it might be a nice addition to vary the line structure for each type of connection by a little

```
 - . - . - . -
 - - - - - -
 . . . . . . . .
 - . . - . . -
 - - . - - . - -
 
 ```
 
 and so on if we add new connections.

**Comment by jessegreenberg** [comment]
Pushed to the dev branch. How is this?
![image](https://github.com/phetsims/paper-land/assets/6396244/90b6469b-5e77-4c39-a5e9-cf1801bcc200)


> If it's simple, it might be a nice addition to vary the line structure for each type of connection by a little

It is simple to play around with `lineDash`. But I think anything else would be a lot more manual drawing code. I made the `lineDash` different for each wire in the canvas and in the legend.

If you want to try out different values, you can play with these:
https://github.com/phetsims/paper-land/blob/d7088a15e9dd1843b27f448f5f7b7baf198f0292/client/creator/view/ViewConstants.js#L89-L94

But if that is no good I will revert that part. Let me know what you think!

**Comment by terracoda** [comment]
Changing the patterns on the dashed lines is a good idea. It means we are not using color alone to communicate meaning!

**Comment by jessegreenberg** [comment]
I just reduced the spacing a bit so it is easier to see the arrow heads. But the constants are still in place to make the line-dashes different for each wire! Feel free to change these however you see fit:

https://github.com/phetsims/paper-land/blob/ec9abd5159ece6467a4f48910efb48346dfe8935/client/creator/view/ViewConstants.js#L91-L95

**Comment by brettfiedler** [comment]
I tried out this arrangement. Was different enough I thought worth pushing (commit: https://github.com/phetsims/paper-land/commit/35f32b68f8b5596735056e282de700cc7c0dda4f)! Currently on `dev` branch

![image](https://github.com/phetsims/paper-land/assets/47331395/3ba8b215-2993-468e-9d87-f0a372dca704)

![image](https://github.com/phetsims/paper-land/assets/47331395/24a72929-7706-4554-9e75-e2f24a58620d)

**Comment by brettfiedler** [comment]
Overall complete, raise issues as needed.
