### ISSUE TITLE
Screen jumped when setting name for marker controller component

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/paper-land#217]
While working with @brettfiedler we saw some flicker while typing the name into a marker controller. It seemed to lose focus and made the screen jump a little. Ill see if I can reproduce the problem.

**Comment by brettfiedler** [comment]
I believe this was when I had the right pane resized a bit smaller, if helpful!

**Comment by jessegreenberg** [comment]
I tried to get this to happen on my machine but could not. I tried creating new marker controller and editing existing ones. I mostly tried setting the name for the component, but also tried other changes to the form.

I tried with a smaller right pane, as well as narrow and shorter window sizes. I tried to use invalid names in case it was the error text popup causing problems/reflow.

I think it is very possible this behavior was downstream of another error that was either fixed or still lurking somewhere. Either way, I think this can be closed until it resurfaces.
