### ISSUE TITLE
Add a console message when paper needs dependencies from another paper

### ISSUE THREAD

**Issue by brettfiedler** [phetsims/paper-land#224]
There is not always a clue in the console or elsewhere when trying to run a project with multiple papers, when one paper is looking for dependencies that exist on another paper program. 

@jessegreenberg suggested we add a console log to cue the user that something is missing!

**Comment by jessegreenberg** [comment]
OK, a warning has been added for this case. A new Property was added to the model that indicates when the boardModel is in a state that it is waiting for new components to be added before attaching some other observer. Unit tests have been added to test this. Closing.
