### ISSUE TITLE
Change "Description" to "Speech" in View Component form

### ISSUE THREAD

**Issue by brettfiedler** [phetsims/paper-land#251]
I believe "Speech" is more recognizable and more acutely the technology we're tapping into with this component. In PhET's use, we will use the "Speech" component to create description and Voicing-like interactions, but I think the "Description" terminology is likely to be confusing to others.

- [ ] Replace "Description" with "Speech" in the View Component form.

**Comment by jessegreenberg** [comment]
OK, Ill rename. Would be best to rename the code references as well.

**Comment by jessegreenberg** [comment]
This was done in the above commit, renamed to 'speech' in the UI and in all code references (DescriptionViewComponent -> SpeechViewComponent, and in generated code).

**Comment by jessegreenberg** [comment]
The rename also hit serialization, breaking old saves that saved things under `descriptionViews`. The above commit is a graceful fallback for that old data.

Its kind of ugly to do this in the loading part of the code, maybe someday there will be better migration support when the data changes.
