### ISSUE TITLE
Deleting (or renaming?) a reference component causes connected Speech component to fail assertion

### ISSUE THREAD

**Issue by brettfiedler** [phetsims/paper-land#256]
https://github.com/phetsims/paper-land/assets/47331395/835cea58-b629-4f3a-8120-da086916bd34

Steps to reproduce:
- Copy toggle-button-responses project from voicing-response-patterns space.
- Delete hintResponse model string component
- Update voiceFocusResponse function code to remove hintResponse.
- Try to Save Changes
- 
[toggle-button-responses.json](https://github.com/phetsims/paper-land/files/15437576/toggle-button-responses.json)

**Comment by jessegreenberg** [comment]
Yes, there is definitely a related bug here. Steps:

1) Create a view component with a dependency on a model component.
2) Delete the model component.
3) Send to playground.
4) Note that the deleted model component will be referred to in the generated code for the view component.

When a dependency is deleted, it should auto-remove itself from components that depend on it.

**Comment by jessegreenberg** [comment]
This has been fixed for the view component, but several other components will have the same problem:

- [ ] NamedDerivedProperty
- [ ] ListenerComponent
- [ ] MultilinkListenerComponent
