### ISSUE TITLE
Add a sound recording feature to Sound Component

### ISSUE THREAD

**Issue by brettfiedler** [phetsims/paper-land#260]
One of the limitations of using the tool in codesign is the length of time it takes to find the appropriate sound. Sometimes, it is easier to find a way to create the sound or a similar sound in the moment, rather than searching the internet.

This is very similar to Scratch's option to record a sound. 

![image](https://github.com/phetsims/paper-land/assets/47331395/78a46d1d-a6c2-44ec-b15b-c903db1d870c)

![image](https://github.com/phetsims/paper-land/assets/47331395/bb495acd-588d-4d6b-84a5-55fbd536b061)
 
![image](https://github.com/phetsims/paper-land/assets/47331395/b35e1dd0-9c55-41a9-b4e8-407bb890dcf9)

I think we should add a small Record, playback, and confirm dialog. Then we can put that recorded sound in `sounds > uploads`.

This should be baked into the Web Audio API. Here's a[ StackOverflow of someone trying to solve the problem including device selection ](https://stackoverflow.com/questions/31264487/web-audio-api-input-from-specific-microphone) (which I suspect we'll run into given our need to select a video device in many cases as well). And a [webaudiodemo example.](https://webaudiodemos.appspot.com/input/index.html)

**Comment by jessegreenberg** [comment]
OK, basic UI to support this is in. From here we can iterate while I add actual web audio recording support. It is in the sound-recording branch. Some screenshots if you don't want to check out the branch.

![image](https://github.com/user-attachments/assets/c08d16f0-c2c1-4d87-80e0-c3323c8d39b4)

![image](https://github.com/user-attachments/assets/ea398970-3ac5-4501-afb1-42681d5f95af)

![image](https://github.com/user-attachments/assets/ad561e6a-487f-4b8e-8aba-96f4ebc6acc0)

![image](https://github.com/user-attachments/assets/f97a4133-fe66-4bbb-9fe6-f07addf70239)


@Ashton-Morris @brettfiedler any thoughts at this point? Any important features missing?

Will we want to name or delete recordings? Where should these be saved, in the uploads? Maybe we should add a way to delete uploaded sounds?

**Comment by Ashton-Morris** [comment]
@jessegreenberg Here is a example of how the incoming volume looking in Overcast. 

https://github.com/user-attachments/assets/0faae6cc-441f-4c00-8717-972439984381

**Comment by jessegreenberg** [comment]
Suggestions from today:

- Add a simple visualization of the incoming sound.
- Add a countdown before recording actually starts.
- Add a name for the recording. Put it in uploads. Include a prefix/suffix that indicate that it is a recording.
- Add a delete button that will be shown when a sound from uploads is selected. Pressing it removes the file from uploads.

**Comment by jessegreenberg** [comment]
This was merged into the main branch.

Features from https://github.com/phetsims/paper-land/issues/260#issuecomment-2289224378 have been added.
I tried to test out various use cases and it seems to be working well for Win 10 Chrome.

@brettfiedler @Ashton-Morris can you please test it? There is a new button to delete uploaded sounds. Should that be added to images as well? Do you notice any problems? Any missing functionality? Any layout or UI changes you would like to make?

**Comment by brettfiedler** [comment]
Certainly seems to work. Can you guess which one is the recorded sound 😉 

https://github.com/user-attachments/assets/2f65bec0-fcba-4f6f-a065-64147e9b3ecc

#### Notes/Questions:

1. I noticed we need to grant mic permission each time - is that necessary or only because we can't tell if permission is already granted?

2. Yeah, I think we can duplicate the delete button for (uploaded) images.

**Comment by jessegreenberg** [comment]
In the above commits, a delete button was added for image uploads. And I pushed a way to skip the permission request once permissions have been granted once.

@brettfiedler can you please check and anything else?

**Comment by brettfiedler** [comment]
It all seems to be functioning to me!
