### ISSUE TITLE
Rename all instances of "board" to "display"

### ISSUE THREAD

**Issue by brettfiedler** [phetsims/paper-land#261]
As it says, it's easier to refer to this as the Display and that's how I've been using it and publishing about it. Let's go ahead and rename everything. Let me know if there are any confusing cases.

**Comment by jessegreenberg** [comment]
I think everything has been renamed. Anything else here @brettfiedler?

**Comment by brettfiedler** [comment]
Need to also rename the docs website, which I will do. Leaving assigned.

**Comment by brettfiedler** [comment]
Ran through the doc site and made these changes.
