### ISSUE TITLE
Recreate Quadrilateral sim integration with new Creator interface

### ISSUE THREAD

**Issue by brettfiedler** [phetsims/paper-land#263]
In Mar 2023 we had a Quadrilateral sim integration going using the raw JS files in PAper Playground using Editor, which enabled us to control the simulation using the corners of a paper.

Let's create two scenarios in Paper Playground, using Custom Code:

1. Four corners of one paper control the four corners of the quad sim
2. Each corner in the quad sim gets its own paper

(old implementation, reflecting scenario #1 above)
![PXL_20230502_231521687](https://github.com/user-attachments/assets/7166f2a3-a1b4-4eea-b091-64815c672bd0)

**Comment by jessegreenberg** [comment]
The old Paper Programs code can be found here: 

https://github.com/phetsims/paper-land/tree/main/paper-programs-backup/quadrilateral-sim-demo

**Comment by jessegreenberg** [comment]
OK, this is ready. There are a couple of ways we can handle the transformation from paper to quadrilateral model coordinates, but I want with one that will scale x and y isometrically. Generally a square in paper space produces a square in the sim. We can play with this if it doesn't feel right.

Here is the project 

[quad.json](https://github.com/user-attachments/files/17067643/quad.json)

I will also put it into the remote database under jg-tests/quadrilateral.

**Comment by jessegreenberg** [comment]
OK @brettfiedler I think this is ready to use!

**Comment by brettfiedler** [comment]
Completed and tested! Thanks.
