### ISSUE TITLE
Do we need to continue to support the standalone DB case?

### ISSUE THREAD

**Issue by jbphet** [phetsims/paper-land#30]
For #5 we have changed the code to work with a remote DB that has a set of available spaces.  These changes are likely to have impacted the ability of papyrus to work correctly if it is set up using a local DB, which is how the original Paper Programs code worked.  Do we need to continue to support the use case where a local DB is set up and used to store the programs?  If so, we will need to regression test this periodically and keep it working.

**Comment by BLFiedler** [comment]
This seems to work in the latest iteration with a local installation of PostgreSQL (v15). I'll check with LV who does not have Postgres installed and see if we can get it running from scratch. If so, we'll consider this complete and I'll make sure it's included in the updates to the README and tutorial.

**Comment by brettfiedler** [comment]
Local installation of PostgreSQL database still works. Some rudimentary instructions are in place in the docs.
