### ISSUE TITLE
Synchronize the remote database to the repo

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/paper-land#33]
We want to be able to open up the Program database to contributions that take advantage of GitHubs security and contribution features. This will synchronize periodically with the database.

Assign after we have the database structured settled.

**Comment by BLFiedler** [comment]
Database structure is in a good place and some needs to synchronize the database to the repo have arisen! 

We discussed the need to:
1. Pull all scripts down to make global changes (e.g., updates to repo name (looking at you #39)) and push back to the database.
2. Have a more reliable way to back up the database outside of the admin panel.

Currently, ElephantSQL compresses the backup of the database nightly for at least a months worth. It is compressed as an .lzo file (https://www.lzop.org). To date, I've downloaded the occasional file and uploaded to our Google Drive which is helpful, but not ideal. ElephantSQL does have a built in "restore" function from any of the listed backup, or you can run a terminal command to restore from an older backup? 

![image](https://user-images.githubusercontent.com/47331395/224870629-0d651865-2a4c-48fb-9964-87c7b1fd2269.png)

Assigning to @jbphet to investigate or ask for additional details.

**Comment by BLFiedler** [comment]
I believe this is complete in its first iteration. There is a way to backup to GitHub and a script for devs to push changes to programs from the IDE back up to the database.

Anything else for the initial goals of this issue @jbphet ?

**Comment by jbphet** [comment]
I think we're good.  Closing.
