### ISSUE TITLE
Change the name of the repository

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/paper-land#39]
We would like to open up the repo going down the line. Papyrus is a fun name, but it doesn't align with the branding of the tool. It also overlaps with the Papyrus coding language and several design tools, including at least one UI design tool.

@jbphet indicated it is not too much work to change the name, but we should do it sooner rather than later.

 Just a few names to toss into the ether:
- **paper-playground** (This has stuck around the most so far and may be the default choice)
- **codevise** (also has code in the name) + suffix (PG, Playground, JS)
- **interaction-playground**
- **copaper**
- **collabopaper**
- **paper-n-play**
- **codesign-playground**
- **script-collab**
- **collabosense** + suffix
- **collaboraction** + something
- **playper**

_Originally posted by @BLFiedler in https://github.com/phetsims/papyrus/issues/26#issuecomment-1428140221_

Ping everyone to discuss. If no preference, we'll go forward with the default: paper-playground.
            
When settled, I'll assign JB/JG to make the change.

**Comment by BLFiedler** [comment]
@jbphet @jessegreenberg @emily-phet @terracoda @Ashton-Morris @Matthew-Moore240

**Comment by jessegreenberg** [comment]
+1 for paper-playground

**Comment by Ashton-Morris** [comment]
+1 for playper

**Comment by terracoda** [comment]
I am good with either playper or paper-playground.

I was just trying to think of it with other contexts like a sentence. 

The playper design tool is ...
The paper-playground design too is...

Lowercase "playper" will be auto-corrected to "player".

Wondering about `PLAYper` or `PlAyPER`.

+1 paper-playground

**Comment by emily-phet** [comment]
It would be ideal if the repo did not have the same name as the tool. That way, people can use X repo to make other tools, without things getting confusing re what's our tool and what's the code that enables it. We can also have different variants or versions of the tool without getting tangled up with the version of the code supporting it. Does that make sense?

**Comment by jessegreenberg** [comment]
I think it would be most clear for us to have the repo name match the name of the tool, which we do for sims. There has been some internal confusion about what to call this, (is it "Papyrus", or "Paper Playground", or "paper-playground-papyrus"?).

But I also understand the cases you described. If we are OK with repo being different from the tool, I vote we keep "papyrus".

**Comment by BLFiedler** [comment]
I can see the case for distancing the tool from the code repository, but I still feel they should be pretty closely aligned (if not identical) for a couple of reasons:

- The goals and spirit of the tool (regardless of feature set, editing modality, detection modality) will remain the same for anyone capturing the code for the tool.
- If we're considering future versions (which I think we are), then we should keep in mind what would be most straightforward in keeping up with any "core" code. We might consider anyone making changes to the editing or detection to be "features" that are enabled in the tool in the same repo.
- If there are multiple versions of the same tool, but they are not being taken away and used for very different purposes, we should consider different organization structures that center on... an organization. See Scratch, Fengari, Processing (p5), etc. This is incompatible with our current structure that puts phetsims at the top level. Alternatively, if we're okay with having multiple repos in phetsims, then if we have e.g., paper-playerground, then versions of the tool just add a suffix. paper-playground-object, paper-playground-blockly, etc. (this is probably an argument for a shorter, but aligned name). This is the most common approach I have seen.
- It's more common than it isn't for open source repository names to reflect the thing the code creates. I'd have to do some searching to find another case. We are trying to revolutionize design tools, not open source ecosystems. So, we should do our best to align where possible.
- If we're having trouble with the difference, than others will to. The README for this repository will describe a tool that can possibly be disambiguated from the repository they're in. If other versions arise, and we are supportive of those versions, we should at that point, be concerned with supporting that version as well as pointing to it in our own documentation.


Sorry, this was rapidly typed while preparing dinner. I'll come back in and edit or we can discuss synchronously.

**Comment by BLFiedler** [comment]
Most importantly, we want to keep the name short and it should not be papyrus. So, here are a few other options

Other options:
- reed (the common name of plants that include the plant papyrus is made of)
- cyperus (the genus of the plant that papyrus is made of)

**Comment by BLFiedler** [comment]
We're changing the repo name to `paper-land`

@jessegreenberg @jbphet , make it happen wherever it needs to happen on GitHub and in the tool code.

Noting, others may need to clone the repo again for their local copies!

**Comment by jessegreenberg** [comment]
- [ ] Make sure all commits are pushed to that repo.
- [ ] On Github.com, go to repo -> Settings -> Options -> "Repository name"  and rename.
- [ ] Rename in `perennial/data/active-repos` and any other perennial data files it occurs in, like `active-runnables`, `active-sims`, `phet-io`, etc. Push the change to perennial and then pull perennial-alias.
- [ ] Delete the old repo
- [ ] Run `perennial/bin/clone-missting/repos.sh`.
- [ ] Update `package.json` accordingly. Including but not necessarily limited to:
  * `name`
  * `repository.url`
  * `phet.requirejsNamespace`
- [ ] Change entry in [responsible_dev.json](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.json).
- [ ] If applicable, "refresh perennial" on phettest.
- [ ] Add the sim to chipper/tsconfig/all/tsconfig.json
- [ ] Remove old repo directories in `chipper/dist/js`, `chipper/dist/declarations`, and `chipper/dist/js-cache-status.json` and and restart your transpiler.
- [ ] Notify Slack channel dev-public that the repo has been renamed. E.g. "I just renamed repository {{OLD_REPO}} to {{NEW_REPO}}. Please pull perennial and perennial-alias, run `clone-missing-repos.sh` at your convenience, remove {{OLD_REPO}} in `chipper/dist/js`, `chipper/dist/declarations`, and `chipper/dist/js-cache-status.json` and restart your transpiler."

**Comment by BLFiedler** [comment]
I believe we'll be skipping many of these as the repo is still not in active repos at this time (at least until it is passing PhET lint). Shouldn't need to notify anyone outside of the paper-playground channel

**Comment by jessegreenberg** [comment]
This was done, and references to papyrus have been removed from the repo and in program code. I posted to the slack group the steps to set up the repo. @jbphet confirmed on slack that its working after the re-clone.

@BLFiedler anything else for this issue?

**Comment by BLFiedler** [comment]
Farewell, papyrus!
