### ISSUE TITLE
Move setup information into this repo

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/paper-land#4]
We have setup instructions in https://docs.google.com/document/d/1FTafPkrvRGmP5Z18pWOW2BmtOR7YH0OtgcsKf5_Wnv8/edit#. Lets move it into github.

**Comment by BLFiedler** [comment]
Hold off here pending results of #5. However, I can translate some of this and update the README.md if it makes sense to.

**Comment by BLFiedler** [comment]
Linking this to progress in #26 where the documentation including the README.md will be updated. I'll use this issue to ping devs about technical info.

**Comment by BLFiedler** [comment]
This is fairly up to date and more will be completed as part of more robust documentation updates. Closing this issue.
