### ISSUE TITLE
Create a tool-specific version of console.log

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/paper-land#48]
In development meeting today, we decided it would be helpful to have a log present on the Board that behaves like console.log. This would let individuals making Programs make debugging notes (and other possible use cases) that were directly visible on the Board without opening up the developer console.

@jbphet noted we could not intercede and copy the developer console (present in the browser developer tools, F12 on windows). We will need to create an analog of console.log. The devs indicated they would also likely still use console.log for transient debugging that designers/users would not necessarily need to see.

The devs also indicated it'd be best to put this behind a query parameter. When implemented, we should have a link to the board with and without this on the landing page (index.html)

Let's go ahead and implement this!

**Comment by jessegreenberg** [comment]
OK, an implementation of this has been added to board. Below the sim Display there is a panel with logging information like this:

![image](https://user-images.githubusercontent.com/6396244/230640614-7c3f9411-7a3d-4d44-8c0e-32c021765eb0.png)


From program code you can use functions like
`phet.paperLand.console.log( string )`
`phet.paperLand.console.warn( string )`
`phet.paperLand.console.error( message )`

and messages will appear in the box and in dev tools.

New messages appear at the bottom of the box and it will auto scroll with new messages unless the user has scrolled up.

The console can be hidden/shown with a checkbox in the board controls panel.

**Comment by jessegreenberg** [comment]
While working with @jbphet we noticed that the auto scrolling of the log forces scroll of the entire page which is kind of annoying.

**Comment by jessegreenberg** [comment]
Fixed in the above commit.

**Comment by jessegreenberg** [comment]
I believe this one can be closed, bugs or other requests can come in through new issues as the feature is exercised.
