### ISSUE TITLE
Add feature to lock down edits to Programs in specific playspaces

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/paper-land#49]
With the number of people now using and editing Programs in the remote database, we should be able to "lock down" edits on certain playspaces to prevent accidental overwrite/deletion. Another part of this safety measure is being implemented in #33 for backups.

We want to be able to prevent users from easily deleting, moving, or overwriting Programs in at least the `templates` playspace.

@jbphet said he had a few ideas. One including read-only access to those playspaces for non-admins. This is a little tricky since playspaces aren't "real", other than being a label in a column beside the Program code and number. Also, individuals could edit the programs in the repo (when #33 is done) and push, avoiding the remote admin requirement.

Not an idea we discussed, but: Might we also consider just adding a "make read only" button to the editor to indicate that a program is complete and should not be edited further without further consideration?

**Comment by jbphet** [comment]
I have added what I think we should call v1 of this feature.  It prevents users from editing files in the spaces listed in the new `restrictedSpacesList.js` file if they don't have the appropriate settings in their `.env` file.

This implementation leverages the previously existing feature that would prevent users from editing files that are already being edited by other users, and behaves in a similar fashion.  After testing it a bit, I realized that there is a bit of a down side to implementation.  I found myself bothered by the fact that I can't access the restricted files at all from the editor if they are restricted (or being edited by someone else).  This could be a problem if someone wanted to review and/or copy portions of a restricted file.  We might want to consider a different behavior, where the files can be viewed and copied, but not changed.  This would be a fair bit more development effort, so I'm turning this over to @BLFiedler to get his opinion.

**Comment by BLFiedler** [comment]
I agree that it feels restrictive and anti-collaborative in its current form.

I discussed this with @jbphet and want to propose a rather large change to the database and interaction flow to the team. Let's pause until after that discussion.

**Comment by BLFiedler** [comment]
We decided in meeting, that in conjunction with changes incoming from #66 and #65, this should be made Read-only instead of completely locking it down with the legacy "in use" feature. Over to the devs to change!

**Comment by jbphet** [comment]
This feature is implemented, included headings above the editor windows on both the main editor page and the camera page that indicate when the loaded files are read only.  @BLFiedler - Can you please test it out a bit and let me know if there are other things needed for this feature?

**Comment by BLFiedler** [comment]
Great! Works as advertised. I locally added more restricted spaces and it all behaved as expected, with appearance of Delete and Save buttons only visible when I have access!

We know this is not ideal for collaboration, but for now it strikes the balance of functional and secure-enough for our purposes. Let's make sure we keep backing things up!
