### ISSUE TITLE
How can we move Programs between Playspaces?

### ISSUE THREAD

**Issue by brettfiedler** [phetsims/paper-land#50]
We're starting to create enough Programs in enough playspaces that there's a need for some more organization, especially now that we can easily duplicate Programs. It'd also be nice to be able to move Programs that are being tested in one playspace, more officially to another such as `templates`.

I tried an SQL query in ElephantSQL but was met with an error. 

> UPDATE programs
> SET spaceName = 'newSpaceName'
> WHERE number =  [programNumber];

@jbphet said he'd investigate!

We might also consider adding a UI component to move a Program from one playspace to another. Maybe similar to the New Program dialog?

Let's figure out the right command to move Programs, then decide if it's frustrating enough to need a UI component.

**Comment by BLFiedler** [comment]
When deciding how to unqiuely identify Programs, we realized that we might run into issues if moving programs from one spaceName to another and they each have the same dot sequence. 

We need to verify what will happen when two dot sequences (paper numbers?) are in the database as a whole (not the same playspace) and if the Projector will choose to run the one in the spaceName you are currently in. 

For now, let's hold off on this. There are bigger fish to fry.

**Comment by BLFiedler** [comment]
Current ideas for future implementation:

1. Confine program detection to current Space. Currently, programs don't run if you're not in the right space anyway, even if the tool recognizes them. We create the possibility for each space to have the full combination of dot sequences by doing this and don't lose any functionality (I think?)

2. Right now we need to copy programs to a new space (which assigns them a new dot sequence) and delete the old one to do a full transfer. Multiselect #65, will make this easier, but someday we might want a Transfer function. Adding to wishlist for now.

**Comment by brettfiedler** [comment]
We prioritized the Creator interface, which enables duplicating projects or creating/applying templates. Since we're not supporting the JavaScript editor and space management from Camera.html anymore, I am closing this issue.
