### ISSUE TITLE
Is it okay to remove code from the printed papers permanently?

### ISSUE THREAD

**Issue by jbphet** [phetsims/paper-land#51]
While working on #22, I came across an issue in `printPdf.js` where there was an unused variable called `code` in the function `drawPage`.  I needed to remove it to pass lint, but it appears that the usage of this variable was commented out by us due to some issues with printing the code on the paper programs.  I don't feel comfortable taking it out permanently without checking in with the rest of the team.  Is it okay for us to fully remove, at least for now, the ability to print the code on the program sheets?

**Comment by BLFiedler** [comment]
From what I can tell, it was never figured out how to print the code to the paper. Something about linewrap.  

I'd prefer to find easier ways to look up the code for a paper in the interface than to have code that is static on the paper (and would be impossible to read in the format I printed my papers for today's examples)

If there's no objection from @jessegreenberg , who I believe made those edits to `printPDF.js`, then we should feel comfortable removing it to pass lint.

**Comment by BLFiedler** [comment]
JG a-okay with this. Go ahead and verify removal, @jbphet!

**Comment by jbphet** [comment]
I removed more of the code related to this feature so we don't have vestigial portions hanging around.  I think this should cover it, closing.
