### ISSUE TITLE
Lots of unused things in AudioGraphSoundView

### ISSUE THREAD

**Issue by jbphet** [phetsims/paper-land#52]
While working on #22 I was seeing a number of failures due to unused items in the file `AudioGraphSoundView.js` . 
 I commented them out to get it to pass lint, but it was a substantial part of the file, so I thought @jessegreenberg should review it. 
 The commit is https://github.com/phetsims/paper-land/commit/5a2976cbe54c8cf25eb81851831933a797f89130.  @jessegreenberg - can you please check this over and permanently remove the items if it is appropriate to do so?

**Comment by jessegreenberg** [comment]
Discussed during stand up meeting today: OK to remove AudioGraphSoundView and all related code. We would like to keep the audio files, but will replace them with smaller versions to help with #1.

**Comment by jessegreenberg** [comment]
OK, all audio graph code from our early prototypes have been removed. Ill replace sound files in #1. Closing.
