### ISSUE TITLE
Add threshold for paper position change for onProgramChangePosition to board

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/paper-land#55]
When testing Density: Change Volume with Paper Area with the Voice Volume Value, we noticed that the small amount of detection jitter caused the volume value to constantly change, even if not intentionally moving the Program. This made the voice interrupt itself constantly to try to read the new value!

NO LONGER TRUE SEE COMMENTS BELOW --We should implement a control in the Camera interface (probably under the Calibration header) to control the minimum amount of marker movement needed to trigger a position change for the paper. This is similar to some work we did in Quadrilateral with OpenCV which we called "Position Interval". -- 

Worth investigating if there is already any averaging/smoothing happening in the code and if we should add that as well. Maybe just note if it exists for now, @jessegreenberg.

**Comment by BLFiedler** [comment]
Recording a snippet of conversation on Slack about this, since it changes the implementation that I originally imagined:

> Jesse Greenberg
> I am wondering if the 'Min Marker Delta' control should be added to the Board page instead of CameraMain since it is specific to our paper-land code?
> 
> Brett Fiedler

> I think it would happen with the marker positioning code regardless of our choice to package in onProgramChangedPosition. I see it as tied to the detection itself and not to the program execution.
> If we built an example with TTS on the projector, I suspect it would do the same thing, yeah? (edited) 
> 
> Jesse Greenberg

> I see - currently the onProgramChangedPosition event is specific to board and was added by us. I was thinking the delta check would happen around here in board code: https://github.com/phetsims/paper-land/blob/5ba85e0bafdffac5504e63acac5582abf6b76173/client/board/entry.js#L65-L71
> 
> Let me see how program positions were originally being saved.
> 
> Brett Fiedler
> Hmm. Yeah. I see how there are two ways to go about this. It's like on one side, we could alter the detection of the marker so the jitter never even "happens", while on the board side, we could filter it out but let the camera/projector retain the same resolution.
> 
> Jesse Greenberg

> Right, exactly
> 
> Brett Fiedler

> I do like the idea of having more control over the detection, since troubleshooting the right lighting conditions can be tricky, but more options there could also be confusing if things are handling themselves well enough right now.
> 
> Well, go ahead and choose whichever seems easier to implement right now. If it's on the board, we can put the control behind the same query as that new console log-like as a helpful debugging tool. Before that's implemented you can plop it anywhere.
> 
> Ultimately it might not hurt to have both down the line. Probably needs a different name though, similar to what you put into the zoom chat "Min Delta onProgramChangePosition" or something

**Comment by BLFiedler** [comment]
Updated title to reflect what we actually hope to accomplish in this issue.

- [ ] We will go ahead with adding an onProgramChangePosition threshold control to board.html.

Someday we’ll likely want to revisit how the legacy tool does marker detection cleanup and consider adding our own (e.g., demystify Accurate -> Precise vagueness and other marker detection parameters). There are several issues in [paperprograms open issues](https://github.com/janpaul123/paperprograms/issues) about doing automatic detection setup (lighting compensation, etc)

**Comment by jessegreenberg** [comment]
This has been added, @BLFiedler can you please try it out and confirm/comment on next steps?

**Comment by jessegreenberg** [comment]
Done, position interval and other board config can be saved to local storage.
