### ISSUE TITLE
Merge editor.html with camera.html

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/paper-land#60]
The Editor and Camera are intricately linked as it is. Their separation results in the duplication of sorting/filtering functionality and decouples the "things you're playing with" from the code. Also, more tabs and windows is just hard given typical screen sizes. Let's merge them together.

There's a lot of empty space under the camera feed. Let's try putting it there. Bonus points if the editor is now responsive to the window size. Not sure if investigating #12 is worth it to update to a newer version of the open source Monaco editor (we're many years out of date at the present).

e.g.,

![image](https://user-images.githubusercontent.com/47331395/228892697-808ec762-22a4-41e3-a816-c020ea9dfc79.png)

We'll need to bring these controls over into the sidebar as well. Perhaps it will be best to split the sidebar into two (ideally that are collapsible/scrollable.

![image](https://user-images.githubusercontent.com/47331395/228893063-ec75a31f-3e67-4509-bcd9-c6b4c8be1022.png)

**Comment by BLFiedler** [comment]
@jbphet is working on this locally. So far, he has the editor showing in the Camera window but it is not interactable yet. He will push it up when it is!

**Comment by jbphet** [comment]
This is mostly working at this point.  I think I'll log a separate issue for the improvements to the sidebar that we discussed this morn, and there is already one for the "delete programs" feature.  @BLFiedler - is there anything else specific to this feature that needs to be done, or can it be closed?

**Comment by BLFiedler** [comment]
Overall this is great in combination with the other changes (buttons, etc). I'd love to hear what @jessegreenberg thinks and if he finds himself working there or still opening the separate editor when creating examples.

Would it be worth be able to make the height of the editor larger or resizable?

**Comment by jessegreenberg** [comment]
This has been nice! Most of my editing has still been in Editor page just because it is nice to have a larger editor when making new programs. For small adjustments I would probably just use the If the Camera page . If it were maybe 2x taller I would probably be fine with just the camera editor.

**Comment by BLFiedler** [comment]
Keeping open for the editor height change (twice as high). Good to close after.

**Comment by jbphet** [comment]
The changes listed in the previous comment have been made, closing.
