### ISSUE TITLE
Expand the Create Program dialog with a preview of the selected Program

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/paper-land#64]
Seeing only the Program names without a reference for what you might be looking for (if you aren't sure exactly what you want, especially outside of the space you're in), can be a bit confusing.

Can we expand the Create Program dialog to show a preview of the **selected** Program when creating a copy of another program? 

This can be on the simpler side since we're not actually interacting with the code. Perhaps we can just take the database entry (string?) and display it with code formatting? Brief google brings up some React blocks: https://github.com/rajinwonderland/react-code-blocks or for bootstrap (since I can't remember what the dialog is): https://www.geeksforgeeks.org/how-to-display-code-with-bootstrap/ 

It's OK to have a button to open a Preview Pane, but we don't want users to have to press Preview on every Program they select.

**Comment by BLFiedler** [comment]
Chatted with @jbphet and I think this is a worthwhile effort (that won't need to be changed) while we make decisions on other priorities. Assigning JB and JG to implement alongside the other Camera changes!

**Comment by jessegreenberg** [comment]
OK, done in the above commit @BLFiedler, can you please test and let us know if anything else is needed?

**Comment by jessegreenberg** [comment]
At one point, we talked about making the preview optional with a checkbox, but having the editor pop in and out felt more distracting to me than it was worth. If you want to make it optional we can still do that.

**Comment by BLFiedler** [comment]
This is great! Calling this good here unless something crops up.
