### ISSUE TITLE
Add ability to delete programs for spaces that are not locked

### ISSUE THREAD

**Issue by brettfiedler** [phetsims/paper-land#66]
We hope to encourage users to copy established example spaces (demos?) when they want to tweak something without worrying about breaking the programs. Since we will have safely locked spaces that are Read Only (which also requires creating a new Space to tinker), and being able to create more than one program at a time (#65), Spaces are likely to get messy quickly. Relying on someone to boot up the remote database to clean things up is not sustainable and may prove frustrating in the moment for users.

Let's posit the following:
1. We will have consistent, timely backups of all programs.
2. We have trust in users with access to the remote database to not delete Programs in unlocked spaces they should not

And then let's create the following feature:

- A button to delete a selected program from Camera.html
- A prompt that appears confirming they want to delete the program "This will remove the program for all users of the database. Are you sure you want to delete this program? "
- Only authenticated users can delete programs from locked/private spaces.

Questions:
- Where should the button live? Above the editor or in the program selection list? 
  - BF: Gut tells me above the editor is better, maybe colored Red, maybe with a little trash icon. The Program list is already crowded and seems prone to misclicks.

**Comment by jbphet** [comment]
I've repositioned the buttons a bit, made the layout more consistent when the buttons are and aren't present, and put the camera and editor into boxes to make it more clear that the editor title & control bar goes with the editor.  @BLFiedler - please have a look and let's talk about whether additional changes are needed under this issue.

**Comment by brettfiedler** [comment]
Very nice QoL, has worked out well to date. Any other changes suggested here I think are out of the scope of this issue and should have other issues. Closing!
