### ISSUE TITLE
Make sidebar on Camera collapsible

### ISSUE THREAD

**Issue by brettfiedler** [phetsims/paper-land#73]
Branching off #60, we'd like to make the sidebar collapsible to maximize the size of the camera view and embedded editor for smaller window sizes.

@jbphet showed options in bootstrap/react that might also allow each sidebar section to be collapsible.

We'll work on collapsing the entire sidebar first.

**Comment by jbphet** [comment]
I have an initial version of this working (and it's pretty cool!).  There are a few oddities that I'd like to refine from the current state:

- [ ] The scroll bar for the sidebar is visible when the sidebar itself is collapsed, which looks odd.
- [ ] A very thin section of the sidebar appears to be visible when it is collapsed.  It would be better if it where completely hidden.
- [ ] I used transitions for the sidebar popping out and back in, which work well, but the sidebar is updating its layout as it pops in or out, which looks odd and is particularly noticeable when the transition time is longer.  It would be better if it somehow stayed at the same width.

**Comment by jbphet** [comment]
Okay, I think this is ready for review by @BLFiedler.

**Comment by brettfiedler** [comment]
This is fantastic and very helpful! Closing.
