### ISSUE TITLE
Voice a static overview or scene summary

### ISSUE THREAD

**Issue by terracoda** [phetsims/paper-land#77]
Inspired by @hypergami 's deep sea diving example, I though it would be good to have a program that voiced some background details that set the scene.

**Comment by jessegreenberg** [comment]
Would let a user design a scene summary before any interactions.

Could print the content on the screen (maybe with the other Print Voicing program)

How about we create a program that is a template with a single string.
That string is spoken when the program is detected.
The program is spoken again when a marker is added.

But, after discussign with @terracoda we thought it could be straight forward to voice static content like this with snippet code taht already exists. So assigning back to @terracoda.
