### ISSUE TITLE
Make the individual sections of the sidebar collapsible

### ISSUE THREAD

**Issue by jbphet** [phetsims/paper-land#79]
In #73 we made the entire sidebar collapsible so that it could be moved out of the way when the user just wants to see the camera and/or editor.  The sidebar is still pretty tall and requires scrolling in many cases to get to what users need, so it would be nice to have the individual regions within it collapsible.

**Comment by BLFiedler** [comment]
The major implementation of this is working and the initial design is a-okay! We'll refine later as needed. Thanks @jbphet!
