### ISSUE TITLE
branch: marker-matching

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/paper-land#83]
WIP for board code to support watching for global marker changes.

Since markers are not uniquely identifiable like programs, is is tricky to support unique events for marker addition, marker removal, and marker position change. To get around this, we added some code to try to track existing markers hand how they are changing between updates. If a marker before and after has the same color and position (within threshold) is is considered to be the same marker.

The trouble with this is that markers of the same color with a distance between them that is smaller than that threshold are considered the same marker.

The two markers on the left hare cannot be uniquely identified:
![image](https://user-images.githubusercontent.com/6396244/235008054-650eeed6-2c84-4e76-9707-0d356ae75ffa.png)

@jbphet suggested that a smarter search for "closest one to the moving marker" might resolve this.

**Comment by jbphet** [comment]
Unassigning myself since I'm moving off of the paper-playground project for the foreseeable future.

**Comment by jessegreenberg** [comment]
This branch has been merged into master. Ill prune it and close this issue.

**Comment by jessegreenberg** [comment]
It is removed. Closing,.
