### ISSUE TITLE
Implement "claim" in editor now on camera screen

### ISSUE THREAD

**Issue by jbphet** [phetsims/paper-land#88]
In https://github.com/phetsims/paper-land/issues/60 we added an editor window to the main camera screen.  There is a feature in the main editor screen where a file is "claimed" using a field in the DB when it is being edited so that multiple people can't edit the file at the same time.  We should probably add the "claim" functionality to the editor on the camera screen.

**Comment by jbphet** [comment]
Assigning to @BLFiedler for prioritization and assignment.

**Comment by brettfiedler** [comment]
Given the difficulty in claiming program editing capabilities across three interfaces (Camera, Editor, and now Creator), we're going to turn the editor in Camera to preview-only. Closing this issue.

https://github.com/phetsims/paper-land/issues/107
