### ISSUE TITLE
Add an indication of unsaved changes and option not to lose those changes in the editors

### ISSUE THREAD

**Issue by jbphet** [phetsims/paper-land#89]
In https://github.com/phetsims/paper-land/issues/60 we added an editor to the camera screen.  Currently, there is no indication of unsaved changes for this editor, though that information is available in the internal state.  Also, a user can select a different program when changes have been made to the previously selected one, and the current UI will happily oblige without giving the user the chance to save the changes.  It would be an improvement to the UI to give the user the option of saving the changes in this scenario.

**Comment by brettfiedler** [comment]
We have de-emphasized the Editors in the latest iterations, in favor of Creator. The editor in Camera has been reduced in functionality to Read Only, so this shouldn't be an issue.
