### ISSUE TITLE
Add some quickstart info for fundamental PhET libraries

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/paper-land#97]
Axon and scenery are used heavily by Board, and we encourage users to create components with these libraries.

Some quickstart documentation that goes over the specific components we expect people to use would probably be very helpful for developers to start using paper-land without needing to go deep into PhET's repos and docs.

**Comment by brettfiedler** [comment]
Had copied this example of info provided in Element to include in the docs before this issue:

> The value setter comes from using phet.axon.Property. So here is one way to fix this:
> 
> ```js
> const myCircleColorProperty = new phet.axon.Property( 'rgb( 255,255,0 )' );
> phet.paperLand.addModelComponent( 'myCircleColorProperty', myCircleColor );
> ```
> 
> Now you can update the value with
> ```js
> phet.paperLand.getModelComponent( 'myCircleColorProperty' ).value = 'rgb(0,0,255)';
> ```
> 
> Using an axon.Property also lets you observe changes to the color with phet.paperLand.addModelPropertyLink.
> 
> But if you would rather not use axon.Property, you could also wrap your string in an object with a value key like this:
> 
> ```js
>     const myCircleColor = { value: 'rgb(255,255,0)' };
>     phet.paperLand.addModelComponent( 'circleColor')
> ```

**Comment by jessegreenberg** [comment]
This seems superseded by more abstracted Creator code, closing for now.
